package de.cau.cs.se.geco.architecture.framework;

import de.cau.cs.se.geco.architecture.framework.IGenerator;

@SuppressWarnings("all")
public class AbstractATLTransformation<S extends Object, T extends Object> implements IGenerator<S, T> {
  @Override
  public T generate(final S input) {
    throw new Error("Unresolved compilation problems:"
      + "\nmismatched input \',\' expecting \'}\'"
      + "\nEMFModelFactory cannot be resolved."
      + "\nXMIResourceFactoryImpl cannot be resolved."
      + "\nThe method or field EMFExtractor is undefined for the type AbstractATLTransformation"
      + "\nThe method or field extractor is undefined for the type AbstractATLTransformation"
      + "\nEMFExtractor cannot be resolved."
      + "\nThe method or field EMFInjector is undefined for the type AbstractATLTransformation"
      + "\nThe method or field emfInjector is undefined for the type AbstractATLTransformation"
      + "\nEMFInjector cannot be resolved."
      + "\nThe method or field ResourceSet is undefined for the type AbstractATLTransformation"
      + "\nThe method or field resourceSet is undefined for the type AbstractATLTransformation"
      + "\nResourceSetImpl cannot be resolved."
      + "\nThe method or field EMFReferenceModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field hdlMetaModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field EMFReferenceModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field emfInjector is undefined for the type AbstractATLTransformation"
      + "\nThe method or field hdlMetaModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field resourceSet is undefined for the type AbstractATLTransformation"
      + "\nThe method or field URI is undefined for the type AbstractATLTransformation"
      + "\nThe method or field EMFModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field hdlData is undefined for the type AbstractATLTransformation"
      + "\nThe method or field EMFModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field hdlMetaModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field EMFReferenceModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field palMetaModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field EMFReferenceModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field emfInjector is undefined for the type AbstractATLTransformation"
      + "\nThe method or field palMetaModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field resourceSet is undefined for the type AbstractATLTransformation"
      + "\nThe method or field URI is undefined for the type AbstractATLTransformation"
      + "\nThe method or field EMFModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field palData is undefined for the type AbstractATLTransformation"
      + "\nThe method or field EMFModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field palMetaModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field palData is undefined for the type AbstractATLTransformation"
      + "\nThe method or field Resource is undefined for the type AbstractATLTransformation"
      + "\nThe method or field xmiResource is undefined for the type AbstractATLTransformation"
      + "\nThe method or field URI is undefined for the type AbstractATLTransformation"
      + "\nThe method or field xmiResource is undefined for the type AbstractATLTransformation"
      + "\nThe method or field hdlModel is undefined for the type AbstractATLTransformation"
      + "\nThe method or field emfInjector is undefined for the type AbstractATLTransformation"
      + "\nThe method or field hdlData is undefined for the type AbstractATLTransformation"
      + "\nThe method or field xmiResource is undefined for the type AbstractATLTransformation"
      + "\nThe method or field InputStream is undefined for the type AbstractATLTransformation"
      + "\nThe method or field asm is undefined for the type AbstractATLTransformation"
      + "\nFileInputStream cannot be resolved."
      + "\nThe method or field EMFVMLauncher is undefined for the type AbstractATLTransformation"
      + "\nThe method or field launcher is undefined for the type AbstractATLTransformation"
      + "\nEMFVMLauncher cannot be resolved."
      + "\nThe method or field HashMap is undefined for the type AbstractATLTransformation"
      + "\nnewReferenceModel cannot be resolved"
      + "\ninject cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ncreateFileURI cannot be resolved"
      + "\nnewModel cannot be resolved"
      + "\nnewReferenceModel cannot be resolved"
      + "\ninject cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ncreateFileURI cannot be resolved"
      + "\nnewModel cannot be resolved"
      + "\nsetIsTarget cannot be resolved"
      + "\ncreateResource cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetContents cannot be resolved"
      + "\naddAll cannot be resolved"
      + "\ngetContents cannot be resolved"
      + "\ninject cannot be resolved"
      + "\n< cannot be resolved");
  }
  
  private Object options;
}
