/*
 * generated by Xtext
 */
package de.cau.cs.se.geco.architecture.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.cau.cs.se.geco.architecture.ui.internal.ArchitectureActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArchitectureExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ArchitectureActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ArchitectureActivator.getInstance().getInjector(ArchitectureActivator.DE_CAU_CS_SE_GECO_ARCHITECTURE_ARCHITECTURE);
	}
	
}
