/**
 * generated by Xtext
 */
package de.cau.cs.se.geco.architecture.validation;

import de.cau.cs.se.geco.architecture.validation.AbstractArchitectureValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ArchitectureValidator extends AbstractArchitectureValidator {
}
