/**
 * generated by Xtext 2.10.0
 */
package de.cau.cs.se.geco.architecture.architecture;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aspect Model</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.cau.cs.se.geco.architecture.architecture.ArchitecturePackage#getAspectModel()
 * @model
 * @generated
 */
public interface AspectModel extends EObject
{
} // AspectModel
