/*
 * generated by Xtext 2.10.0
 */
package de.cau.cs.se.geco.architecture.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArchitectureScopeProvider extends DelegatingScopeProvider {
}
