/**
 * generated by Xtext
 */
package de.cau.cs.se.geco.architecture.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class ArchitectureQuickfixProvider extends DefaultQuickfixProvider {
}
