/**
 * generated by Xtext 2.10.0
 */
package de.cau.cs.se.geco.architecture.ui;

import de.cau.cs.se.geco.architecture.ui.AbstractArchitectureUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ArchitectureUiModule extends AbstractArchitectureUiModule {
  public ArchitectureUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
