/*
 * generated by Xtext 2.10.0
 */
package de.cau.cs.se.geco.architecture.parser.antlr;

import com.google.inject.Inject;
import de.cau.cs.se.geco.architecture.parser.antlr.internal.InternalArchitectureParser;
import de.cau.cs.se.geco.architecture.services.ArchitectureGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ArchitectureParser extends AbstractAntlrParser {

	@Inject
	private ArchitectureGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalArchitectureParser createParser(XtextTokenStream stream) {
		return new InternalArchitectureParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GecoModel";
	}

	public ArchitectureGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArchitectureGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
