/*
 * generated by Xtext 2.21.0
 */
package de.cau.cs.se.geco.architecture.tests

import com.google.inject.Inject
import de.cau.cs.se.geco.architecture.architecture.GecoModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(ArchitectureInjectorProvider)
class ArchitectureParsingTest {
	@Inject
	ParseHelper<GecoModel> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			package example
		''')
		Assertions.assertNotNull(result)
	}
}
