/**
 * generated by Xtext 2.10.0
 */
package de.cau.cs.se.geco.architecture.ui.labeling;

import com.google.inject.Inject;
import de.cau.cs.se.geco.architecture.architecture.Generator;
import de.cau.cs.se.geco.architecture.architecture.ModelSequence;
import de.cau.cs.se.geco.architecture.architecture.Weaver;
import de.cau.cs.se.geco.architecture.typing.ArchitectureTyping;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class ArchitectureLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public ArchitectureLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final ModelSequence sequence) {
    return ArchitectureTyping.resolveType(sequence.getType()).getSimpleName();
  }
  
  public String text(final Generator generator) {
    String _simpleName = generator.getReference().getSimpleName();
    return ("generator " + _simpleName);
  }
  
  public String text(final Weaver weaver) {
    String _simpleName = weaver.getReference().getSimpleName();
    return ("weaver " + _simpleName);
  }
}
