/**
 * generated by Xtext
 */
package de.cau.cs.se.geco.architecture.ui.contentassist;

import de.cau.cs.se.geco.architecture.ui.contentassist.AbstractArchitectureProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ArchitectureProposalProvider extends AbstractArchitectureProposalProvider {
}
